apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-st
spec:
  selector:
    matchLabels:
      app: redis # has to match .spec.template.metadata.labels
  serviceName: redis
  template:
    metadata:
      name: redis
      labels:
       app: redis
    spec:
      containers:
        - name: container-redis
          image: redis:alpine
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-persistent-storage
              mountPath: /data
      volumes:
        - name: redis-persistent-storage
          persistentVolumeClaim:
            claimName: redis-pv-claim