
# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rideshare-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rideshare
  template:
    metadata:
      labels:
        app: rideshare
    spec:
      serviceAccountName: ksa-cloud-sql
      containers:
      - name: rideshare-app
        # Replace $LOCATION with your Artifact Registry location (e.g., us-west1).
        # Replace $GCLOUD_PROJECT with your project ID.
        image: asia-southeast1-docker.pkg.dev/rideshare-389010/rideshare-repo/rideshare-gke:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: appenv
        # imagePullPolicy: "Always"
        # This app listens on port 8181 for web traffic by default.
        ports:
        - containerPort: 8181
        env:
          - name: PORT
            value: "8181"
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rideshare-dev-secrets
                key: mysql_password
          - name: MAILGUN_SECRET
            valueFrom:
              secretKeyRef:
                name: rideshare-dev-secrets
                key: mailgun_secret
      - name: cloud-sql-proxy
        # This uses the latest version of the Cloud SQL proxy
        # It is recommended to use a specific version for production environments.
        # See: https://github.com/GoogleCloudPlatform/cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:latest
        command:
          - "/cloud_sql_proxy"

          # If connecting from a VPC-native GKE cluster, you can use the
          # following flag to have the proxy connect over private IP
          # - "-ip_address_types=PRIVATE"

          # tcp should be set to the port the proxy should listen on
          # and should match the DB_PORT value set above.
          # Defaults: MySQL: 3306, Postgres: 5432, SQLServer: 1433
          - "-instances=rideshare-389010:asia-southeast1:rideshare-db=tcp:3306"
        securityContext:
          # The default Cloud SQL proxy image runs as the
          # "nonroot" user and group (uid: 65532) by default.
          runAsNonRoot: true